/* Generated By:JavaCC: Do not edit this line. BasedConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BasedConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int MULTIPLY = 7;
  /** RegularExpression Id. */
  int DIVIDE = 8;
  /** RegularExpression Id. */
  int DEFINE = 9;
  /** RegularExpression Id. */
  int IGNORE = 10;
  /** RegularExpression Id. */
  int LAMBDA = 11;
  /** RegularExpression Id. */
  int ASSIGN = 12;
  /** RegularExpression Id. */
  int EQUAL = 13;
  /** RegularExpression Id. */
  int LESS = 14;
  /** RegularExpression Id. */
  int GREATER = 15;
  /** RegularExpression Id. */
  int LEQ = 16;
  /** RegularExpression Id. */
  int GEQ = 17;
  /** RegularExpression Id. */
  int AND = 18;
  /** RegularExpression Id. */
  int OR = 19;
  /** RegularExpression Id. */
  int NOT = 20;
  /** RegularExpression Id. */
  int INTEGER = 21;
  /** RegularExpression Id. */
  int DIGIT = 22;
  /** RegularExpression Id. */
  int TRUE = 23;
  /** RegularExpression Id. */
  int FALSE = 24;
  /** RegularExpression Id. */
  int READ = 25;
  /** RegularExpression Id. */
  int WRITE = 26;
  /** RegularExpression Id. */
  int NEWLINE = 27;
  /** RegularExpression Id. */
  int CONTAINS = 28;
  /** RegularExpression Id. */
  int ADD = 29;
  /** RegularExpression Id. */
  int SWAP = 30;
  /** RegularExpression Id. */
  int SET = 31;
  /** RegularExpression Id. */
  int IDENTIFIER = 32;
  /** RegularExpression Id. */
  int INITIAL = 33;
  /** RegularExpression Id. */
  int SUBSEQUENT = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"::\"",
    "\"!!\"",
    "\"=>\"",
    "\"->\"",
    "\"==\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\" >=\"",
    "\"&&\"",
    "\"||\"",
    "\"~\"",
    "<INTEGER>",
    "<DIGIT>",
    "\"#t\"",
    "\"#f\"",
    "\"read\"",
    "\"write\"",
    "\"newline\"",
    "\"contains\"",
    "\"add\"",
    "\"swap\"",
    "\"set\"",
    "<IDENTIFIER>",
    "<INITIAL>",
    "<SUBSEQUENT>",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"?\"",
    "\":\"",
    "\"|\"",
    "\"()\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
  };

}
